/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor.pb-c.h"
void   sensor_data__init
                     (SensorData         *message)
{
  static const SensorData init_value = SENSOR_DATA__INIT;
  *message = init_value;
}
size_t sensor_data__get_packed_size
                     (const SensorData *message)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_data__pack
                     (const SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_data__pack_to_buffer
                     (const SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorData *
       sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorData *)
     protobuf_c_message_unpack (&sensor_data__descriptor,
                                allocator, len, data);
}
void   sensor_data__free_unpacked
                     (SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensor_data__field_descriptors[2] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_data__field_indices_by_name[] = {
  1,   /* field[1] = humidity */
  0,   /* field[0] = temperature */
};
static const ProtobufCIntRange sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Sensor_data",
  "SensorData",
  "SensorData",
  "",
  sizeof(SensorData),
  2,
  sensor_data__field_descriptors,
  sensor_data__field_indices_by_name,
  1,  sensor_data__number_ranges,
  (ProtobufCMessageInit) sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
